# Generated by Django 5.2 on 2025-04-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('description', models.TextField(default='-', verbose_name='description')),
                ('price', models.IntegerField(default=10000, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': ('Course',),
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='content title')),
                ('description', models.TextField(default='-', verbose_name='description')),
                ('video_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='video URL')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.course', verbose_name='course')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.coursecontent', verbose_name='parent')),
            ],
            options={
                'verbose_name': ('Course Content',),
                'verbose_name_plural': 'Course Contents',
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('std', 'Student'), ('ast', 'Assistant')], default='std', max_length=3, verbose_name='roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.course', verbose_name='course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': ('Course Member',),
                'verbose_name_plural': ('Course Members',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecontent', verbose_name='content')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursemember', verbose_name='member')),
            ],
            options={
                'verbose_name': ('Comment',),
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
